export const TOOL_NAMES = [
  "ast_check",
  "ast_check_batch",
  "ast_corpus_hash",
  "ast_file_facts",
  "closure_compute",
  "closure_resolve",
  "closure_resolve_batch",
  "closure_unresolved",
  "codex_accept_rule",
  "codex_aspects",
  "codex_corpus_mark",
  "codex_export",
  "codex_fixture_add",
  "codex_fixture_list",
  "codex_gaps",
  "codex_history",
  "codex_import",
  "codex_retire_rule",
  "codex_revert",
  "codex_rule_get",
  "codex_rule_write",
  "codex_rules_for",
  "codex_taxonomy_set",
  "escalation_open",
  "escalation_raise",
  "escalation_resolve",
  "gates_evaluate",
  "gates_status",
  "ledger_finding_known",
  "ledger_finding_upsert",
  "ledger_finding_upsert_batch",
  "ledger_matrix_upsert",
  "ledger_overturn_record",
  "ledger_pass_record",
  "ledger_run_end",
  "ledger_run_start",
  "ledger_state",
  "ledger_unit_upsert",
  "ledger_unit_upsert_batch",
  "ledger_verdict_record",
  "ledger_verdict_record_batch",
  "ledger_waiver_record",
  "ledger_waiver_record_batch",
  "mutation_apply_and_run",
  "mutation_attribution",
  "mutation_batch_run",
  "mutation_campaign_start",
  "mutation_campaign_status",
  "mutation_campaign_stop",
  "mutation_equivalence_record",
  "mutation_generate",
  "mutation_survivors",
  "runner_flake_probe",
  "runner_gate_static",
  "runner_run_suite",
] as const;

export type ToolName = (typeof TOOL_NAMES)[number];

const KNOWN: ReadonlySet<string> = new Set<string>(TOOL_NAMES);

export const isToolName = (value: unknown): value is ToolName =>
  typeof value === "string" && KNOWN.has(value);
